import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
  es: { 
    inicio: "Inicio", 
    tienda: "Tienda", 
    tituloHero: "NanoCoral - Sistemas Premium",
    descripcion: "Especialistas en arrecifes y corales seleccionados.",
    agregarProducto: "Agregar Producto", 
    cerrarFormulario: "Cerrar Formulario",
    nombrePlaceholder: "Nombre del Producto",
    guardarProducto: "Guardar Producto",
    alertaExito: "Producto agregado exitosamente.",
    alertaError: "Error al guardar.",
    descripcionHero: "Sistemas premium de iluminación, corales seleccionados a mano y todo lo necesario para tu pico reef.",
    btnExplorar: "Explorar Tienda",
    tituloDiseno: "¿No sabes cómo empezar?",
    descDiseno: "Expertos en diseño, montaje e instalación técnica a domicilio. Garantiza la estabilidad de tu nuevo ecosistema desde el primer día.",
    tituloMantenimiento: "Servicio de mantenimiento",
    descMantenimiento: "Monitoreo químico, cambios de agua y limpieza profunda para tus corales. Tú solo disfruta, nosotros nos encargamos.",
    btnContactar: "Contactar",
    waMsgDiseno: "Hola, quiero info sobre diseño y montaje.",
    waMsgMantenimiento: "Hola, quiero info sobre mantenimiento.",
    tituloOpiniones: "Opiniones de la Comunidad",
    cargandoTestimonios: "Cargando testimonios...",
    carrito: "Carrito",
    altPezPayaso: "Pez Payaso NanoCoral",
    cargandoCatalogo: "Cargando catálogo...",
    tituloCatalogo: "Catálogo",
    filtroTodos: "Todos",
    filtroPeces: "Peces",
    filtroCorales: "Corales",
    filtroLamparas: "Lámparas",
    btnDetalles: "Detalles",
    btnAgregar: "Agregar",
    tituloCarrito: "Tu Carrito",
    articulos: "artículos",
    carritoVacio: "Tu carrito está vacío.",
    tituloLogin: "Iniciar Sesión",
    placeholderEmail: "Email",
    placeholderPass: "Contraseña",
    btnEntrar: "Entrar",
    alertaBienvenido: "¡Bienvenido!",
    alertaError: "Credenciales incorrectas",
    agregarProducto: "Agregar Producto",
    cerrarFormulario: "Cerrar Formulario",
    nombrePlaceholder: "Nombre del producto",
    precioPlaceholder: "Precio",
    descPlaceholder: "Descripción",
    catPlaceholder: "ID de categoría",
    imgPlaceholder: "URL de la imagen",
    guardarProducto: "Guardar Producto",
    alertaExito: "Producto guardado con éxito",
    alertaError: "Error al guardar el producto",
    cargandoFicha: "Cargando ficha técnica...",
    prodNoEncontrado: "Producto no encontrado.",
    stockStatus: "NanoCoral Premium Stock",
    descDefault: "Ejemplar o equipo seleccionado bajo controles estrictos para asegurar el correcto balance biológico y químico en tu setup marino.",
    btnCarrito: "Agregar al carrito",
    tituloRelacionados: "Productos relacionados",
    btnVerArticulo: "Ver artículo"
  },
  en: { 
    inicio: "Home", 
    tienda: "Shop", 
    tituloHero: "NanoCoral - Premium Systems",
    descripcion: "Specialists in reefs and hand-picked corals.",
    agregarProducto: "Add Product", 
    cerrarFormulario: "Close Form",
    nombrePlaceholder: "Product Name",
    guardarProducto: "Save Product",
    alertaExito: "Product added successfully.",
    alertaError: "Error saving product.",
    descripcionHero: "Premium lighting systems, hand-picked corals, and everything you need for your pico reef.",
    btnExplorar: "Explore Shop",
    tituloDiseno: "Don't know where to start?",
    descDiseno: "Experts in design, assembly, and home technical installation. Guarantee the stability of your new ecosystem from day one.",
    tituloMantenimiento: "Maintenance Service",
    descMantenimiento: "Chemical monitoring, water changes, and deep cleaning for your corals. You just enjoy, we take care of the rest.",
    btnContactar: "Contact Us",
    waMsgDiseno: "Hi, I want info about design and setup.",
    waMsgMantenimiento: "Hi, I want info about maintenance.",
    tituloOpiniones: "Community Reviews",
    cargandoTestimonios: "Loading testimonials...",
    carrito: "Cart",
    altPezPayaso: "NanoCoral Clownfish",
    cargandoCatalogo: "Loading catalog...",
    tituloCatalogo: "Catalog",
    filtroTodos: "All",
    filtroPeces: "Fish",
    filtroCorales: "Corals",
    filtroLamparas: "Lighting",
    btnDetalles: "Details",
    btnAgregar: "Add",
    tituloCarrito: "Your Cart",
    articulos: "items",
    carritoVacio: "Your cart is empty.",
    tituloLogin: "Login",
    placeholderEmail: "Email",
    placeholderPass: "Password",
    btnEntrar: "Sign In",
    alertaBienvenido: "Welcome!",
    alertaError: "Invalid credentials",
    agregarProducto: "Add Product",
    cerrarFormulario: "Close Form",
    nombrePlaceholder: "Product name",
    precioPlaceholder: "Price",
    descPlaceholder: "Description",
    catPlaceholder: "Category ID",
    imgPlaceholder: "Image URL",
    guardarProducto: "Save Product",
    alertaExito: "Product saved successfully",
    alertaError: "Error saving the product",
    cargandoFicha: "Loading technical data...",
    prodNoEncontrado: "Product not found.",
    stockStatus: "NanoCoral Premium Stock",
    descDefault: "Specimen or equipment selected under strict controls to ensure the correct biological and chemical balance in your marine setup.",
    btnCarrito: "Add to cart",
    tituloRelacionados: "Related products",
    btnVerArticulo: "View item"
  },
  de: { 
    inicio: "Startseite", 
    tienda: "Shop", 
    tituloHero: "NanoCoral - Premium Systeme",
    descripcion: "Spezialisten für Riffe und handverlesene Korallen.",
    agregarProducto: "Produkt hinzufügen",
    cerrarFormulario: "Formular schließen",
    nombrePlaceholder: "Produktname",
    guardarProducto: "Produkt speichern",
    alertaExito: "Produkt erfolgreich hinzugefügt.",
    alertaError: "Fehler beim Speichern.",
    descripcionHero: "Premium-Beleuchtungssysteme, handverlesene Korallen und alles, was Sie für Ihr Pico-Riff benötigen.",
    btnExplorar: "Shop Erkunden",
    tituloDiseno: "Sie wissen nicht, wo Sie anfangen sollen?",
    descDiseno: "Experten für Design, Montage und technische Installation vor Ort. Garantieren Sie vom ersten Tag an die Stabilität Ihres neuen Ökosystems.",
    tituloMantenimiento: "Wartungsservice",
    descMantenimiento: "Chemische Überwachung, Wasserwechsel und Tiefenreinigung für Ihre Korallen. Genießen Sie einfach, wir kümmern uns um den Rest.",
    btnContactar: "Kontakt",
    waMsgDiseno: "Hallo, ich möchte Infos zu Design und Montage.",
    waMsgMantenimiento: "Hallo, ich möchte Infos zur Wartung.",
    tituloOpiniones: "Community-Bewertungen",
    cargandoTestimonios: "Testimonials werden geladen...",
    carrito: "Warenkorb",
    altPezPayaso: "NanoCoral Clownfisch",
    cargandoCatalogo: "Katalog wird geladen...",
    tituloCatalogo: "Katalog",
    filtroTodos: "Alle",
    filtroPeces: "Fische",
    filtroCorales: "Korallen",
    filtroLamparas: "Beleuchtung",
    btnDetalles: "Details",
    btnAgregar: "Hinzufügen",
    tituloCarrito: "Warenkorb",
    articulos: "Artikel",
    carritoVacio: "Dein Warenkorb ist leer.",
    tituloLogin: "Anmelden",
    placeholderEmail: "E-Mail",
    placeholderPass: "Passwort",
    btnEntrar: "Einloggen",
    alertaBienvenido: "Willkommen!",  
    alertaError: "Ungültige Anmeldedaten",
    agregarProducto: "Produkt hinzufügen",
    cerrarFormulario: "Formular schließen",
    nombrePlaceholder: "Produktname",
    precioPlaceholder: "Preis",
    descPlaceholder: "Beschreibung",
    catPlaceholder: "Kategorie-ID",
    imgPlaceholder: "Bild-URL",
    guardarProducto: "Produkt speichern",
    alertaExito: "Produkt erfolgreich gespeichert",
    alertaError: "Fehler beim Speichern des Produkts",
    cargandoFicha: "Datenblatt wird geladen...",
    prodNoEncontrado: "Produkt nicht gefunden.",
    stockStatus: "NanoCoral Premium Bestand",
    descDefault: "Exemplar oder Ausrüstung, ausgewählt unter strengen Kontrollen, um das korrekte biologische und chemische Gleichgewicht in Ihrem Meerwasser-Setup zu gewährleisten.",
    btnCarrito: "In den Warenkorb",
    tituloRelacionados: "Verwandte Produkte",
    btnVerArticulo: "Artikel ansehen"
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('es');
  const t = (key) => translations[lang]?.[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);